### ISSUE TITLE
Blog Post Images take long to load

### ISSUE THREAD

**Issue by nathanyoung** [IronFoundry/ironfoundry.github.io#11]
Not sure why, but blog post images are really slow to load.

**Comment by adrienlo-T3** [comment]
Going to have to run some importer to import all the images from wordpress.

**Comment by adrienlo-T3** [comment]
I've downloaded all the images from wordpress to `/img/blog/`, just need to update the links in all the blog post.

**Comment by adrienlo-T3** [comment]
Blog images all point to the relative paths now and are local and hosted on GH Pages.
