### ISSUE TITLE
Downloads - fix links to point to new help system

### ISSUE THREAD

**Issue by jaredwray** [IronFoundry/ironfoundry.github.io#16]
We need to fix links to point to the new help system. Right now they are going to help.ironfoundry.org which we are getting rid of. 

We need to fix the "Release Notes" and "Documentation" on all downloads

**Comment by jaredwray** [comment]
fixed current issue and pointed them to help.ironfoundry.org.

Now we need to fix the downloads to point to the legacy locations.

**Comment by lukebakken** [comment]
The links on http://app.ironfoundry.me/download are fixed, but the help page still has links to help.ironfoundry.org:

http://www.ironfoundry.org/help.html#legacy-cloud-foundry-explorer
