### ISSUE TITLE
Signup - Terms of Service not Working

### ISSUE THREAD

**Issue by jaredwray** [IronFoundry/ironfoundry.github.io#18]
http://app.ironfoundry.me/terms

We need to add the terms of service to the General caterogy on the help system.

http://ironfoundry.github.io/help.html

**Comment by jaredwray** [comment]
Need to update the application

**Comment by lukebakken** [comment]
I'll get it, it must have been removed accidentally.

**Comment by lukebakken** [comment]
I also re-added acceptance of the TOS it to the app on signup.

http://app.ironfoundry.me/signup
