### ISSUE TITLE
Recaptcha needs to be updated.

### ISSUE THREAD

**Issue by lukebakken** [IronFoundry/ironfoundry.github.io#2]
The referer needs to be updated to `app.ironfoundry.org`

**Comment by adrienlo-T3** [comment]
Where do I update this?

**Comment by lukebakken** [comment]
I got it. Right now the recaptcha keys are associated with my google account. We should make a google account using the well-known ironfoundry email address (team@ironfoundry.org I think) and re-generate the keys from there. Ask Jared about getting that google account made.
