### ISSUE TITLE
Download page toolkit layout broken

### ISSUE THREAD

**Issue by osbornm** [IronFoundry/ironfoundry.github.io#24]
Buttons are touching and the text goes off screen. Using Chrome on OSX

![screen shot 2013-08-14 at 11 11 00 am](https://f.cloud.github.com/assets/674284/963977/0fc3a0ea-050d-11e3-92e5-cae9e0c3a3d9.png)

**Comment by adrienlo-T3** [comment]
Fixed with commit 47699cb3bf8d13bb8d87d9e91e72059dd3d06b46
