### ISSUE TITLE
change pages to not have html extensions

### ISSUE THREAD

**Issue by jaredwray** [IronFoundry/ironfoundry.github.io#27]
Can we change it so that help.html and about.html arent the main urls. I would like to make it also so that it is /blog and not /blog/index.html

**Comment by adrienlo-T3** [comment]
Root pages no longer have extensions. The blog pages like `/blog/page2.html, etc` and help docs are generated. I can take a look at how to hide that if that's a problem.

**Comment by jaredwray** [comment]
confirmed and closing
