### ISSUE TITLE
DNS updates

### ISSUE THREAD

**Issue by lukebakken** [IronFoundry/ironfoundry.github.io#4]
DNS needs to have records created:

`app.ironfoundry.org` -> `66.150.99.28`

or a CNAME to app.ironfoundry.me will work. This is only if we don't want to use `ironfoundry.me`

In addition, there will have to be DNS updates for the `ironfoundry.gitub.io` GH pages site:

https://help.github.com/articles/setting-up-a-custom-domain-with-pages

**Comment by jaredwray** [comment]
Done and Done!

@lukebakken @nathanyoung @rseroter @shanturoy @adrienlo-T3
