### ISSUE TITLE
Blog Pagination Labels

### ISSUE THREAD

**Issue by nathanyoung** [IronFoundry/ironfoundry.github.io#9]
I think the labels are backwards. Currently, "newer posts" links to older posts and vice-versa. Should be the other way around.

![screen shot 2013-08-08 at 5 07 54 pm](https://f.cloud.github.com/assets/1447339/935556/c8b059a2-0087-11e3-8952-5a8404c79115.png)

**Comment by adrienlo-T3** [comment]
Do you mean they should flip sides? The links work correctly for me.

**Comment by nathanyoung** [comment]
No, the link is labeled "newer posts" but it actually takes you back in time. The "older posts" link takes you to newer posts.

**Comment by adrienlo-T3** [comment]
Wait. Nevermind. Got it.
